from pb import ei_pb2

BOOST_ITEMS: list[ei_pb2.LiveConfig.BoostsConfig.ItemConfig] = [
	ei_pb2.LiveConfig.BoostsConfig.ItemConfig(
		boost_id="jimbos_blue_v2",
		price=50,
		token_price=0,
		se_required=0
	),
	ei_pb2.LiveConfig.BoostsConfig.ItemConfig(
		boost_id="jimbos_purple_v2",
		price=150,
		token_price=1,
		se_required=0
	),
	ei_pb2.LiveConfig.BoostsConfig.ItemConfig(
		boost_id="jimbos_purple_big",
		price=750,
		token_price=1,
		se_required=1
	),
	ei_pb2.LiveConfig.BoostsConfig.ItemConfig(
		boost_id="jimbos_orange",
		price=2500,
		token_price=2,
		se_required=100
	),
	ei_pb2.LiveConfig.BoostsConfig.ItemConfig(
		boost_id="jimbos_orange_big",
		price=7500,
		token_price=3,
		se_required=100
	),
	ei_pb2.LiveConfig.BoostsConfig.ItemConfig(
		boost_id="subsidy_application",
		price=200,
		token_price=1,
		se_required=0
	),
	ei_pb2.LiveConfig.BoostsConfig.ItemConfig(
		boost_id="blank_check",
		price=750,
		token_price=1,
		se_required=100000
	),
	ei_pb2.LiveConfig.BoostsConfig.ItemConfig(
		boost_id="money_printer",
		price=2500,
		token_price=2,
		se_required=5000000
	),
	ei_pb2.LiveConfig.BoostsConfig.ItemConfig(
		boost_id="tachyon_prism_blue_v2",
		price=50,
		token_price=0,
		se_required=0
	),
	ei_pb2.LiveConfig.BoostsConfig.ItemConfig(
		boost_id="tachyon_prism_blue_big",
		price=500,
		token_price=0,
		se_required=0
	),
	ei_pb2.LiveConfig.BoostsConfig.ItemConfig(
		boost_id="tachyon_prism_purple_v2",
		price=1000,
		token_price=2,
		se_required=0
	),
	ei_pb2.LiveConfig.BoostsConfig.ItemConfig(
		boost_id="tachyon_prism_purple_big",
		price=5000,
		token_price=2,
		se_required=100
	),
	ei_pb2.LiveConfig.BoostsConfig.ItemConfig(
		boost_id="tachyon_prism_orange",
		price=12000,
		token_price=4,
		se_required=2500
	),
	ei_pb2.LiveConfig.BoostsConfig.ItemConfig(
		boost_id="tachyon_prism_orange_big",
		price=25000,
		token_price=4,
		se_required=100000
	),
	ei_pb2.LiveConfig.BoostsConfig.ItemConfig(
		boost_id="soul_beacon_blue_v2",
		price=200,
		token_price=0,
		se_required=10000
	),
	ei_pb2.LiveConfig.BoostsConfig.ItemConfig(
		boost_id="soul_beacon_purple_v2",
		price=1000,
		token_price=0,
		se_required=1000000
	),
	ei_pb2.LiveConfig.BoostsConfig.ItemConfig(
		boost_id="soul_beacon_orange",
		price=10000,
		token_price=0,
		se_required=10000000000
	),
	ei_pb2.LiveConfig.BoostsConfig.ItemConfig(
		boost_id="boost_beacon_blue",
		price=1000,
		token_price=1,
		se_required=1000
	),
	ei_pb2.LiveConfig.BoostsConfig.ItemConfig(
		boost_id="boost_beacon_purple",
		price=8000,
		token_price=4,
		se_required=100000
	),
	ei_pb2.LiveConfig.BoostsConfig.ItemConfig(
		boost_id="boost_beacon_blue_big",
		price=15000,
		token_price=3,
		se_required=500000
	),
	ei_pb2.LiveConfig.BoostsConfig.ItemConfig(
		boost_id="boost_beacon_orange",
		price=50000,
		token_price=8,
		se_required=100000000
	),
	ei_pb2.LiveConfig.BoostsConfig.ItemConfig(
		boost_id="soul_mirror_blue",
		price=100,
		token_price=1,
		se_required=1000
	),
	ei_pb2.LiveConfig.BoostsConfig.ItemConfig(
		boost_id="soul_mirror_purple",
		price=500,
		token_price=2,
		se_required=1000
	),
	ei_pb2.LiveConfig.BoostsConfig.ItemConfig(
		boost_id="soul_mirror_orange",
		price=2000,
		token_price=3,
		se_required=10000
	),
	ei_pb2.LiveConfig.BoostsConfig.ItemConfig(
		boost_id="quantum_bulb",
		price=10,
		token_price=0,
		se_required=0
	),
	ei_pb2.LiveConfig.BoostsConfig.ItemConfig(
		boost_id="dilithium_bulb",
		price=1000,
		token_price=0,
		se_required=100000
	),
	ei_pb2.LiveConfig.BoostsConfig.ItemConfig(
		boost_id="jimbos_blue",
		price=50,
		token_price=1,
		se_required=0
	),
	ei_pb2.LiveConfig.BoostsConfig.ItemConfig(
		boost_id="jimbos_blue_big",
		price=100,
		token_price=1,
		se_required=0
	),
	ei_pb2.LiveConfig.BoostsConfig.ItemConfig(
		boost_id="jimbos_purple",
		price=250,
		token_price=2,
		se_required=0
	),
	ei_pb2.LiveConfig.BoostsConfig.ItemConfig(
		boost_id="tachyon_prism_blue",
		price=200,
		token_price=1,
		se_required=0
	),
	ei_pb2.LiveConfig.BoostsConfig.ItemConfig(
		boost_id="tachyon_prism_purple",
		price=1000,
		token_price=3,
		se_required=0
	),
	ei_pb2.LiveConfig.BoostsConfig.ItemConfig(
		boost_id="soul_beacon_blue",
		price=200,
		token_price=0,
		se_required=10000
	),
	ei_pb2.LiveConfig.BoostsConfig.ItemConfig(
		boost_id="soul_beacon_purple",
		price=1000,
		token_price=0,
		se_required=1000000
	)
]
GIFT_CONFIGS: list[ei_pb2.LiveConfig.GiftConfig.GiftValueConfig] = [
	ei_pb2.LiveConfig.GiftConfig.GiftValueConfig(
		gift_id="ge_half_dozen",
		rand_min=0.1,
		rand_max=0,
		amount=6,
		video_min=0,
		video_max=0,
	)
]