from pb.ei_pb2 import *

# LiveConfig Stuff
BOOST_ITEMS: list[LiveConfig.BoostsConfig.ItemConfig] = [
	LiveConfig.BoostsConfig.ItemConfig(
		boost_id="jimbos_blue_v2",
		price=50,
		token_price=0,
		se_required=0
	),
	LiveConfig.BoostsConfig.ItemConfig(
		boost_id="jimbos_purple_v2",
		price=150,
		token_price=1,
		se_required=0
	),
	LiveConfig.BoostsConfig.ItemConfig(
		boost_id="jimbos_purple_big",
		price=750,
		token_price=1,
		se_required=1
	),
	LiveConfig.BoostsConfig.ItemConfig(
		boost_id="jimbos_orange",
		price=2500,
		token_price=2,
		se_required=100
	),
	LiveConfig.BoostsConfig.ItemConfig(
		boost_id="jimbos_orange_big",
		price=7500,
		token_price=3,
		se_required=100
	),
	LiveConfig.BoostsConfig.ItemConfig(
		boost_id="subsidy_application",
		price=200,
		token_price=1,
		se_required=0
	),
	LiveConfig.BoostsConfig.ItemConfig(
		boost_id="blank_check",
		price=750,
		token_price=1,
		se_required=100000
	),
	LiveConfig.BoostsConfig.ItemConfig(
		boost_id="money_printer",
		price=2500,
		token_price=2,
		se_required=5000000
	),
	LiveConfig.BoostsConfig.ItemConfig(
		boost_id="tachyon_prism_blue_v2",
		price=50,
		token_price=0,
		se_required=0
	),
	LiveConfig.BoostsConfig.ItemConfig(
		boost_id="tachyon_prism_blue_big",
		price=500,
		token_price=0,
		se_required=0
	),
	LiveConfig.BoostsConfig.ItemConfig(
		boost_id="tachyon_prism_purple_v2",
		price=1000,
		token_price=2,
		se_required=0
	),
	LiveConfig.BoostsConfig.ItemConfig(
		boost_id="tachyon_prism_purple_big",
		price=5000,
		token_price=2,
		se_required=100
	),
	LiveConfig.BoostsConfig.ItemConfig(
		boost_id="tachyon_prism_orange",
		price=12000,
		token_price=4,
		se_required=2500
	),
	LiveConfig.BoostsConfig.ItemConfig(
		boost_id="tachyon_prism_orange_big",
		price=25000,
		token_price=4,
		se_required=100000
	),
	LiveConfig.BoostsConfig.ItemConfig(
		boost_id="soul_beacon_blue_v2",
		price=200,
		token_price=0,
		se_required=10000
	),
	LiveConfig.BoostsConfig.ItemConfig(
		boost_id="soul_beacon_purple_v2",
		price=1000,
		token_price=0,
		se_required=1000000
	),
	LiveConfig.BoostsConfig.ItemConfig(
		boost_id="soul_beacon_orange",
		price=10000,
		token_price=0,
		se_required=10000000000
	),
	LiveConfig.BoostsConfig.ItemConfig(
		boost_id="boost_beacon_blue",
		price=1000,
		token_price=1,
		se_required=1000
	),
	LiveConfig.BoostsConfig.ItemConfig(
		boost_id="boost_beacon_purple",
		price=8000,
		token_price=4,
		se_required=100000
	),
	LiveConfig.BoostsConfig.ItemConfig(
		boost_id="boost_beacon_blue_big",
		price=15000,
		token_price=3,
		se_required=500000
	),
	LiveConfig.BoostsConfig.ItemConfig(
		boost_id="boost_beacon_orange",
		price=50000,
		token_price=8,
		se_required=100000000
	),
	LiveConfig.BoostsConfig.ItemConfig(
		boost_id="soul_mirror_blue",
		price=100,
		token_price=1,
		se_required=1000
	),
	LiveConfig.BoostsConfig.ItemConfig(
		boost_id="soul_mirror_purple",
		price=500,
		token_price=2,
		se_required=1000
	),
	LiveConfig.BoostsConfig.ItemConfig(
		boost_id="soul_mirror_orange",
		price=2000,
		token_price=3,
		se_required=10000
	),
	LiveConfig.BoostsConfig.ItemConfig(
		boost_id="quantum_bulb",
		price=10,
		token_price=0,
		se_required=0
	),
	LiveConfig.BoostsConfig.ItemConfig(
		boost_id="dilithium_bulb",
		price=1000,
		token_price=0,
		se_required=100000
	),
	LiveConfig.BoostsConfig.ItemConfig(
		boost_id="jimbos_blue",
		price=50,
		token_price=1,
		se_required=0
	),
	LiveConfig.BoostsConfig.ItemConfig(
		boost_id="jimbos_blue_big",
		price=100,
		token_price=1,
		se_required=0
	),
	LiveConfig.BoostsConfig.ItemConfig(
		boost_id="jimbos_purple",
		price=250,
		token_price=2,
		se_required=0
	),
	LiveConfig.BoostsConfig.ItemConfig(
		boost_id="tachyon_prism_blue",
		price=200,
		token_price=1,
		se_required=0
	),
	LiveConfig.BoostsConfig.ItemConfig(
		boost_id="tachyon_prism_purple",
		price=1000,
		token_price=3,
		se_required=0
	),
	LiveConfig.BoostsConfig.ItemConfig(
		boost_id="soul_beacon_blue",
		price=200,
		token_price=0,
		se_required=10000
	),
	LiveConfig.BoostsConfig.ItemConfig(
		boost_id="soul_beacon_purple",
		price=1000,
		token_price=0,
		se_required=1000000
	)
]
GIFT_CONFIGS: list[LiveConfig.GiftConfig.GiftValueConfig] = [
	LiveConfig.GiftConfig.GiftValueConfig(
		gift_id="ge_half_dozen",
		rand_min=0.1,
		rand_max=0,
		amount=6,
		video_min=0,
		video_max=0,
	)
]

# Artifacts Stuff
MISSION_PARAMETERS: list[ArtifactsConfigurationResponse.MissionParameters] = [
    ArtifactsConfigurationResponse.MissionParameters(
        ship=MissionInfo.Spaceship.CHICKEN_ONE,
        durations=[
            ArtifactsConfigurationResponse.MissionParameters.Duration(
                duration_type=MissionInfo.DurationType.TUTORIAL,
                seconds=60,
                capacity=4,
            ),
            ArtifactsConfigurationResponse.MissionParameters.Duration(
                duration_type=MissionInfo.DurationType.SHORT,
                seconds=60*20,
                capacity=4,
            ),
            ArtifactsConfigurationResponse.MissionParameters.Duration(
                duration_type=MissionInfo.DurationType.LONG,
                seconds=60*60,
                capacity=5,
            ),
            ArtifactsConfigurationResponse.MissionParameters.Duration(
                duration_type=MissionInfo.DurationType.EPIC,
                seconds=60*60*2,
                capacity=6,
            ),
        ]
    )
]